a=float(input('So tien ban dau:'))
b=int(input('So thang gui:'))
c=float(input('Lai suat/ thang:'))
print('Voi so tien ban dau',str(a)+', sau',b,'thang gui,','lai suat',str(c)+'/ thang')
print('Thi so tien nhan duoc cuoi ky la:',a*(1+b*c))